# Generated by Django 4.1.9 on 2023-12-20 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_versions", "0004_fileversion_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="hash_value",
            field=models.CharField(default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="user",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
